services:
  postgres:
    image: postgres:latest
    ports:
      - 12345:5432
    volumes:
      - $DB_DIR:/var/lib/postgresql/data
    env_file:
      - ../postgres/.env
  main:
    build: ../..
    depends_on:
      - postgres
    env_file:
      - .env
      - ../postgres/.env
